# Generated by Django 5.2.17 on 2026-08-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short name for the task.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional details about what needs to be done.')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', help_text='How urgent this task is.', max_length=4)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'In Progress'), ('DONE', 'Done')], default='TODO', help_text='Current progress of the task.', max_length=5)),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline for the task.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the task was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last edit.')),
            ],
            options={
                'ordering': ['status', '-priority', 'due_date'],
            },
        ),
    ]
